-- 0001 — polaris-email initial consolidated schema (greenfield).
--
-- This file replaces the 27 incremental migrations (0001-0027) that were
-- collapsed during greenfield consolidation. Every table, view, index,
-- trigger, and CHECK constraint reflects the post-0027 end-state.
--
-- Author new migrations as 0002+. Do NOT edit this file post-deploy —
-- if you need a schema change, append a new migration.

PRAGMA foreign_keys = OFF;

-- ============================================================================
-- Bookkeeping
-- ============================================================================

CREATE TABLE schema_migrations (
  version    INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL,
  sha        TEXT NOT NULL
);

CREATE TABLE bootstrap (
  id                     INTEGER PRIMARY KEY CHECK(id = 1),
  consumed_at            TEXT,
  admin_key_id           TEXT,
  webauthn_credential_id TEXT
);

CREATE TABLE cron_runs (
  job_name    TEXT PRIMARY KEY,
  last_run_at TEXT NOT NULL,
  status      TEXT NOT NULL CHECK(status IN ('ok','error','skipped')),
  duration_ms INTEGER NOT NULL DEFAULT 0,
  message     TEXT
);

-- ============================================================================
-- Zones + mail domains
-- ============================================================================

CREATE TABLE zones (
  id         TEXT PRIMARY KEY,
  cf_zone_id TEXT NOT NULL UNIQUE,
  name       TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL
);

CREATE TABLE mail_domains (
  id                                TEXT PRIMARY KEY,
  zone_id                           TEXT NOT NULL REFERENCES zones(id),
  parent_domain_id                  TEXT REFERENCES mail_domains(id),
  name                              TEXT NOT NULL UNIQUE,
  status                            TEXT NOT NULL DEFAULT 'pending'
                                      CHECK(status IN ('pending','verifying','verified','failed','disabled')),
  wildcard_subdomains               INTEGER NOT NULL DEFAULT 1,
  dmarc_policy                      TEXT,
  dmarc_rua                         TEXT,
  inbound_enabled                   INTEGER NOT NULL DEFAULT 0,
  outbound_enabled                  INTEGER NOT NULL DEFAULT 0,
  provider                          TEXT NOT NULL DEFAULT 'cloudflare'
                                      CHECK(provider IN ('cloudflare')),
  cf_zone_id                        TEXT,
  dkim_selector                     TEXT DEFAULT 'cf',
  created_at                        TEXT NOT NULL,
  updated_at                        TEXT NOT NULL,
  verified_at                       TEXT,
  last_verify_check_at              TEXT,
  disabled_at                       TEXT,
  -- MTA-STS (RFC 8461). Intent flags at create-time; the per-domain
  -- /mta-sts/enable endpoint flips the live state.
  mta_sts_mode                      TEXT NOT NULL DEFAULT 'none'
                                      CHECK(mta_sts_mode IN ('none','testing','enforce')),
  mta_sts_policy_id                 TEXT,
  mta_sts_max_age                   INTEGER NOT NULL DEFAULT 86400,
  mta_sts_verified_at               TEXT,
  -- TLS-RPT (RFC 8460).
  tlsrpt_enabled                    INTEGER NOT NULL DEFAULT 0,
  tlsrpt_rua                        TEXT,
  tlsrpt_verified_at                TEXT,
  -- DMARC promotion state machine (W8).
  dmarc_promotion_mode              TEXT NOT NULL DEFAULT 'auto'
                                      CHECK(dmarc_promotion_mode IN ('auto','manual','paused')),
  dmarc_promotion_state             TEXT NOT NULL DEFAULT 'none'
                                      CHECK(dmarc_promotion_state IN (
                                        'none',
                                        'quarantine_ready',
                                        'quarantine',
                                        'reject_ready',
                                        'reject',
                                        'paused'
                                      )),
  dmarc_promotion_last_at           TEXT,
  dmarc_record_managed_by_polaris   INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX idx_mail_domains_zone_id        ON mail_domains(zone_id);
CREATE INDEX idx_mail_domains_parent         ON mail_domains(parent_domain_id);
CREATE INDEX idx_mail_domains_status         ON mail_domains(status);
CREATE INDEX idx_mail_domains_mta_sts_mode   ON mail_domains(mta_sts_mode);
CREATE INDEX idx_mail_domains_dmarc_promotion ON mail_domains(dmarc_promotion_state);

CREATE TABLE dkim_keys (
  id           TEXT PRIMARY KEY,
  domain_id    TEXT NOT NULL REFERENCES mail_domains(id),
  selector     TEXT NOT NULL,
  public_key   TEXT NOT NULL,
  algo         TEXT NOT NULL CHECK(algo IN ('ed25519','rsa2048')),
  state        TEXT NOT NULL CHECK(state IN ('pending','active','retiring')),
  activated_at TEXT,
  retired_at   TEXT,
  created_at   TEXT NOT NULL,
  UNIQUE(domain_id, selector)
);
CREATE INDEX idx_dkim_keys_domain_id ON dkim_keys(domain_id);
CREATE INDEX idx_dkim_keys_state     ON dkim_keys(state);

-- ============================================================================
-- Mailbox plane
-- ============================================================================

CREATE TABLE mailboxes (
  id                TEXT PRIMARY KEY,
  name              TEXT NOT NULL UNIQUE,
  description       TEXT,
  default_sender_id TEXT REFERENCES mailbox_senders(id),
  created_at        TEXT NOT NULL,
  updated_at        TEXT NOT NULL,
  disabled_at       TEXT
);
CREATE INDEX idx_mailboxes_disabled_at ON mailboxes(disabled_at);

CREATE TABLE mailbox_senders (
  id                  TEXT PRIMARY KEY,
  mailbox_id          TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
  domain_id           TEXT NOT NULL REFERENCES mail_domains(id),
  address             TEXT NOT NULL UNIQUE,
  local_part          TEXT,
  display_name        TEXT,
  default_for_mailbox INTEGER NOT NULL DEFAULT 0,
  created_at          TEXT NOT NULL,
  disabled_at         TEXT
);
CREATE INDEX idx_mailbox_senders_mailbox_id ON mailbox_senders(mailbox_id);
CREATE INDEX idx_mailbox_senders_domain_id  ON mailbox_senders(domain_id);
CREATE INDEX idx_mailbox_senders_address_active
  ON mailbox_senders(address) WHERE disabled_at IS NULL;

CREATE TABLE mailbox_receivers (
  id              TEXT PRIMARY KEY,
  mailbox_id      TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
  domain_id       TEXT NOT NULL REFERENCES mail_domains(id),
  priority        INTEGER NOT NULL DEFAULT 100,
  address_pattern TEXT NOT NULL,
  action          TEXT NOT NULL CHECK(action IN ('webhook','forward','drop')),
  webhook_sub_id  TEXT REFERENCES webhook_subs(id) ON DELETE SET NULL,
  forward_to      TEXT,
  enabled         INTEGER NOT NULL DEFAULT 1,
  created_at      TEXT NOT NULL,
  disabled_at     TEXT
);
CREATE INDEX idx_mailbox_receivers_mailbox_id ON mailbox_receivers(mailbox_id);
CREATE INDEX idx_mailbox_receivers_domain_priority
  ON mailbox_receivers(domain_id, priority, address_pattern)
  WHERE enabled = 1 AND disabled_at IS NULL;

-- ============================================================================
-- Credential plane
-- ============================================================================

CREATE TABLE principals (
  id           TEXT PRIMARY KEY,
  mailbox_id   TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
  kind         TEXT NOT NULL CHECK(kind IN ('api_key','smtp_cred')),
  display_name TEXT,
  created_at   TEXT NOT NULL,
  disabled_at  TEXT
);
CREATE INDEX idx_principals_mailbox_id ON principals(mailbox_id);
CREATE INDEX idx_principals_kind       ON principals(kind);

CREATE TABLE api_keys (
  id                 TEXT PRIMARY KEY,
  principal_id       TEXT NOT NULL REFERENCES principals(id) ON DELETE CASCADE,
  prefix             TEXT NOT NULL,
  secret_argon2id    TEXT NOT NULL,
  scopes             TEXT NOT NULL,
  rate_limit_per_min INTEGER NOT NULL DEFAULT 60,
  status             TEXT NOT NULL DEFAULT 'primary'
                       CHECK(status IN ('primary','secondary','revoked')),
  created_at         TEXT NOT NULL,
  last_used_at       TEXT,
  last_used_ip       TEXT,
  last_used_ua       TEXT,
  revoked_at         TEXT,
  disabled_at        TEXT
);
CREATE INDEX idx_api_keys_principal_id ON api_keys(principal_id);
CREATE INDEX idx_api_keys_status       ON api_keys(status);

CREATE TABLE api_key_sender_scopes (
  api_key_id TEXT NOT NULL REFERENCES api_keys(id) ON DELETE CASCADE,
  sender_id  TEXT NOT NULL REFERENCES mailbox_senders(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL,
  PRIMARY KEY (api_key_id, sender_id)
);
CREATE INDEX idx_api_key_sender_scopes_sender ON api_key_sender_scopes(sender_id);

CREATE TABLE submission_credentials (
  id           TEXT PRIMARY KEY,
  principal_id TEXT NOT NULL REFERENCES principals(id) ON DELETE CASCADE,
  sender_id    TEXT NOT NULL REFERENCES mailbox_senders(id) ON DELETE CASCADE,
  bridge_id    TEXT,
  username     TEXT NOT NULL UNIQUE,
  bcrypt_hash  TEXT NOT NULL,
  created_at   TEXT NOT NULL,
  last_used_at TEXT,
  disabled_at  TEXT
);
CREATE INDEX idx_submission_credentials_principal_id ON submission_credentials(principal_id);
CREATE INDEX idx_submission_credentials_sender_id    ON submission_credentials(sender_id);
CREATE INDEX idx_submission_credentials_bridge_id    ON submission_credentials(bridge_id);

CREATE TABLE mailbox_credentials (
  id           TEXT PRIMARY KEY,
  mailbox_id   TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
  protocol     TEXT NOT NULL CHECK(protocol IN ('imap','smtps')),
  auth_type    TEXT NOT NULL CHECK(auth_type IN ('password')),
  username     TEXT NOT NULL,
  bcrypt_hash  TEXT NOT NULL,
  created_at   TEXT NOT NULL,
  last_used_at TEXT,
  disabled_at  TEXT,
  UNIQUE(mailbox_id, protocol, username)
);
CREATE INDEX idx_mailbox_credentials_mailbox_id ON mailbox_credentials(mailbox_id);
CREATE INDEX idx_mailbox_credentials_protocol   ON mailbox_credentials(mailbox_id, protocol);

-- ============================================================================
-- Bridges (on-prem mail-bridge registry)
-- ============================================================================

CREATE TABLE bridges (
  id                   TEXT PRIMARY KEY,
  name                 TEXT NOT NULL UNIQUE,
  hmac_key_secret_name TEXT,
  access_token_id      TEXT,
  last_seen_at         TEXT,
  created_at           TEXT NOT NULL,
  disabled_at          TEXT
);

-- ============================================================================
-- Webhook plane
-- ============================================================================

CREATE TABLE webhook_subs (
  id                TEXT PRIMARY KEY,
  mailbox_id        TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
  url               TEXT NOT NULL,
  kind              TEXT NOT NULL DEFAULT 'external'
                      CHECK(kind IN ('external','tailnet')),
  secret            TEXT NOT NULL,
  secret_prev       TEXT,
  events            TEXT NOT NULL,
  paused_at         TEXT,
  created_at        TEXT NOT NULL,
  disabled_at       TEXT,
  secret_rotated_at TEXT
);
CREATE INDEX idx_webhook_subs_mailbox_id ON webhook_subs(mailbox_id);

-- ============================================================================
-- Message plane
-- ============================================================================

CREATE TABLE messages (
  id                      TEXT PRIMARY KEY,
  mailbox_id              TEXT NOT NULL REFERENCES mailboxes(id),
  principal_id            TEXT REFERENCES principals(id),
  bridge_id               TEXT REFERENCES bridges(id),
  direction               TEXT NOT NULL CHECK(direction IN ('in','out')),
  status                  TEXT NOT NULL CHECK(status IN (
                            'received','mime_stored','queued','sending',
                            'sent','bounced','delivered','failed','held'
                          )),
  from_addr               TEXT NOT NULL,
  from_addr_normalized    TEXT GENERATED ALWAYS AS (LOWER(from_addr)) STORED,
  to_addrs                TEXT,
  subject                 TEXT,
  r2_key                  TEXT NOT NULL,
  content_sha256          TEXT NOT NULL,
  parsed_json             TEXT,
  body_bytes              INTEGER,
  attachments_total_bytes INTEGER,
  idempotency_key         TEXT,
  message_id_header       TEXT,
  header_message_id       TEXT,
  thread_id               TEXT,
  send_attempt_id         TEXT,
  received_at_bridge      TEXT,
  received_at_api         TEXT,
  queued_at               TEXT,
  sending_at              TEXT,
  sent_at                 TEXT,
  delivered_at            TEXT,
  failed_at               TEXT,
  bounced_at              TEXT,
  bounce_metadata         TEXT,
  last_error              TEXT,
  auth_spf                TEXT,
  auth_dkim               TEXT,
  auth_dmarc              TEXT,
  auth_remote_ip          TEXT,
  stream_type             TEXT NOT NULL DEFAULT 'transactional'
                            CHECK(stream_type IN ('transactional','marketing','agent','inbound')),
  policy_decision_id      TEXT,
  created_at              TEXT NOT NULL
);
CREATE INDEX idx_messages_mailbox_created       ON messages(mailbox_id, created_at DESC);
CREATE INDEX idx_messages_mailbox_dir_status    ON messages(mailbox_id, direction, status);
CREATE INDEX idx_messages_mailbox_status_created ON messages(mailbox_id, status, created_at DESC);
CREATE INDEX idx_messages_direction_status_at   ON messages(direction, status, created_at DESC);
CREATE INDEX idx_messages_from_normalized       ON messages(from_addr_normalized);
CREATE INDEX idx_messages_content_sha256        ON messages(content_sha256);
CREATE INDEX idx_messages_idempotency_key       ON messages(idempotency_key);
CREATE INDEX idx_messages_mailbox_thread        ON messages(mailbox_id, thread_id, created_at DESC);
CREATE INDEX idx_messages_header_message_id     ON messages(header_message_id);
CREATE INDEX idx_messages_policy_decision       ON messages(policy_decision_id);
CREATE INDEX idx_messages_stream_type           ON messages(stream_type, created_at DESC);

CREATE TABLE message_attempts (
  id              TEXT PRIMARY KEY,
  message_id      TEXT NOT NULL REFERENCES messages(id),
  send_attempt_id TEXT,
  attempted_at    TEXT NOT NULL,
  succeeded       INTEGER NOT NULL,
  error           TEXT
);
CREATE INDEX idx_message_attempts_message_id ON message_attempts(message_id);

CREATE TABLE message_deliveries (
  message_id         TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  webhook_sub_id     TEXT NOT NULL REFERENCES webhook_subs(id) ON DELETE CASCADE,
  status             TEXT NOT NULL CHECK(status IN ('pending','succeeded','failed','dlq')),
  attempts           INTEGER NOT NULL DEFAULT 0,
  next_attempt_at    TEXT,
  last_error         TEXT,
  last_response_code INTEGER,
  created_at         TEXT NOT NULL,
  PRIMARY KEY (message_id, webhook_sub_id)
);
CREATE INDEX idx_message_deliveries_status ON message_deliveries(status);

CREATE TABLE webhook_dlq (
  id               TEXT PRIMARY KEY,
  message_id       TEXT REFERENCES messages(id) ON DELETE SET NULL,
  webhook_sub_id   TEXT NOT NULL REFERENCES webhook_subs(id) ON DELETE CASCADE,
  payload_sha256   TEXT NOT NULL,
  last_status_code INTEGER,
  last_error       TEXT,
  attempts         INTEGER NOT NULL DEFAULT 0,
  dlq_at           TEXT NOT NULL,
  replayed_at      TEXT,
  dropped_at       TEXT
);
CREATE INDEX idx_webhook_dlq_sub_id ON webhook_dlq(webhook_sub_id);
CREATE INDEX idx_webhook_dlq_dlq_at ON webhook_dlq(dlq_at);

CREATE TABLE idempotency_keys (
  principal_id TEXT NOT NULL,
  key          TEXT NOT NULL,
  mailbox_id   TEXT NOT NULL REFERENCES mailboxes(id),
  message_id   TEXT REFERENCES messages(id),
  expires_at   TEXT,
  created_at   TEXT NOT NULL,
  claim_locked INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (principal_id, key)
);
CREATE INDEX idx_idempotency_keys_expires_at ON idempotency_keys(expires_at);
CREATE INDEX idx_idempotency_keys_mailbox_id ON idempotency_keys(mailbox_id);

-- ============================================================================
-- IMAP-side state (bridge mirror keeps a local copy)
-- ============================================================================

CREATE TABLE mailbox_messages_state (
  message_id   TEXT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  mailbox_id   TEXT NOT NULL REFERENCES mailboxes(id) ON DELETE CASCADE,
  read_at      TEXT,
  expunged_at  TEXT,
  flags_json   TEXT NOT NULL DEFAULT '[]',
  uid          INTEGER NOT NULL,
  uid_validity INTEGER NOT NULL,
  change_id    INTEGER NOT NULL,
  PRIMARY KEY (mailbox_id, message_id)
);
CREATE INDEX idx_mailbox_messages_state_change   ON mailbox_messages_state(mailbox_id, change_id);
CREATE INDEX idx_mailbox_messages_state_uid      ON mailbox_messages_state(mailbox_id, uid);
CREATE INDEX idx_mailbox_messages_state_expunged ON mailbox_messages_state(mailbox_id, expunged_at);

CREATE TABLE mailbox_uid_counter (
  mailbox_id   TEXT PRIMARY KEY REFERENCES mailboxes(id) ON DELETE CASCADE,
  next_uid     INTEGER NOT NULL DEFAULT 1,
  uid_validity INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER))
);

CREATE TABLE mailbox_change_counter (
  mailbox_id     TEXT PRIMARY KEY REFERENCES mailboxes(id) ON DELETE CASCADE,
  next_change_id INTEGER NOT NULL DEFAULT 1
);

-- ============================================================================
-- Suppressions + abuse events + admin alerts + sender abuse profile
-- ============================================================================

CREATE TABLE suppressions (
  id                 TEXT PRIMARY KEY,
  entity_type        TEXT NOT NULL CHECK(entity_type IN ('recipient','sender')),
  address_normalized TEXT NOT NULL,
  address_local      TEXT,
  address_domain     TEXT,
  scope              TEXT NOT NULL DEFAULT 'global'
                       CHECK(scope IN ('global','domain','mailbox','sender_address')),
  scope_target       TEXT,
  reason             TEXT NOT NULL CHECK(reason IN (
                       'hard_bounce',
                       'spam_complaint',
                       'unsubscribe',
                       'manual',
                       'arf_complaint',
                       'phishing_report',
                       'sender_abuse_threshold',
                       'role_account',
                       'invalid'
                     )),
  source             TEXT NOT NULL CHECK(source IN (
                       'cf_email_service',
                       'arf_inbox',
                       'one_click',
                       'cli',
                       'panel',
                       'import',
                       'sender_threshold_cron',
                       'llm_triage'
                     )),
  source_ref         TEXT,
  severity           TEXT NOT NULL DEFAULT 'warn'
                       CHECK(severity IN ('info','warn','critical')),
  created_at         TEXT NOT NULL,
  expires_at         TEXT,
  disabled_at        TEXT,
  disabled_reason    TEXT,
  notes              TEXT
);
CREATE INDEX        idx_suppressions_lookup  ON suppressions(entity_type, address_normalized);
CREATE INDEX        idx_suppressions_scope   ON suppressions(entity_type, scope, scope_target, address_normalized);
CREATE INDEX        idx_suppressions_reason  ON suppressions(reason, created_at DESC);
CREATE INDEX        idx_suppressions_created ON suppressions(created_at DESC);
CREATE UNIQUE INDEX idx_suppressions_active_unique
  ON suppressions(entity_type, address_normalized, scope, COALESCE(scope_target, ''))
  WHERE disabled_at IS NULL;

CREATE TABLE abuse_events (
  id                          TEXT PRIMARY KEY,
  sender_address              TEXT,
  sender_principal_mailbox_id TEXT REFERENCES mailboxes(id),
  sender_principal_sender_id  TEXT REFERENCES mailbox_senders(id),
  sender_principal_domain_id  TEXT REFERENCES mail_domains(id),
  classification              TEXT NOT NULL CHECK(classification IN (
                                'spam_complaint','phishing_report','virus',
                                'auth_failure','opt_out','hard_bounce',
                                'legal_takedown','mailing_list_admin','other'
                              )),
  source                      TEXT NOT NULL CHECK(source IN (
                                'arf_inbox','llm_triage','cf_bounce_webhook',
                                'cf_email_service','panel','cli','import'
                              )),
  source_ref                  TEXT,
  weight                      INTEGER NOT NULL DEFAULT 1,
  reporter_address            TEXT,
  reporter_org                TEXT,
  original_message_id         TEXT,
  raw_meta                    TEXT NOT NULL DEFAULT '{}',
  caused_suppression_id       TEXT,
  reported_at                 TEXT NOT NULL,
  created_at                  TEXT NOT NULL
);
CREATE INDEX idx_abuse_events_sender_address ON abuse_events(sender_address, reported_at DESC);
CREATE INDEX idx_abuse_events_mailbox        ON abuse_events(sender_principal_mailbox_id, reported_at DESC);
CREATE INDEX idx_abuse_events_sender_id      ON abuse_events(sender_principal_sender_id, reported_at DESC);
CREATE INDEX idx_abuse_events_domain         ON abuse_events(sender_principal_domain_id, reported_at DESC);
CREATE INDEX idx_abuse_events_classification ON abuse_events(classification, reported_at DESC);
CREATE INDEX idx_abuse_events_reported_at    ON abuse_events(reported_at DESC);

CREATE TABLE admin_alerts (
  id         TEXT PRIMARY KEY,
  alert_type TEXT NOT NULL CHECK(alert_type IN (
               'sender_suppressed',
               'phishing_report_received',
               'legal_takedown_received',
               'sender_threshold_breached',
               'tls_rpt_failure_burst',
               'dmarc_alignment_drop',
               'synthetic_check_failed',
               'manual'
             )),
  severity   TEXT NOT NULL DEFAULT 'warn'
               CHECK(severity IN ('info','warn','critical')),
  target     TEXT NOT NULL,
  subject    TEXT NOT NULL,
  body       TEXT NOT NULL,
  delivery   TEXT NOT NULL DEFAULT '[]',
  payload    TEXT NOT NULL DEFAULT '{}',
  dedupe_key TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX idx_admin_alerts_type     ON admin_alerts(alert_type, created_at DESC);
CREATE INDEX idx_admin_alerts_severity ON admin_alerts(severity, created_at DESC);
CREATE INDEX idx_admin_alerts_target   ON admin_alerts(target, created_at DESC);
CREATE INDEX idx_admin_alerts_dedupe   ON admin_alerts(dedupe_key, created_at DESC);
CREATE INDEX idx_admin_alerts_created  ON admin_alerts(created_at DESC);

CREATE TABLE sender_abuse_profile (
  principal_type          TEXT NOT NULL CHECK(principal_type IN ('sender_address','mailbox','domain')),
  principal_id            TEXT NOT NULL,
  lifetime_event_count    INTEGER NOT NULL DEFAULT 0,
  lifetime_weighted_score INTEGER NOT NULL DEFAULT 0,
  suppression_count       INTEGER NOT NULL DEFAULT 0,
  current_tier            INTEGER NOT NULL DEFAULT 0
                            CHECK(current_tier >= 0 AND current_tier <= 5),
  current_tier_started_at TEXT,
  last_suppressed_at      TEXT,
  last_event_at           TEXT,
  notes                   TEXT,
  created_at              TEXT NOT NULL,
  updated_at              TEXT NOT NULL,
  PRIMARY KEY (principal_type, principal_id)
);
CREATE INDEX idx_sender_abuse_profile_tier       ON sender_abuse_profile(current_tier DESC);
CREATE INDEX idx_sender_abuse_profile_last_event ON sender_abuse_profile(last_event_at DESC);

-- ============================================================================
-- TLS-RPT + DMARC ingest
-- ============================================================================

CREATE TABLE tls_rpt_reports (
  id                  TEXT PRIMARY KEY,
  domain              TEXT,
  organization_name   TEXT,
  contact_info        TEXT,
  report_id           TEXT,
  date_range_start    TEXT,
  date_range_end      TEXT,
  total_success_count INTEGER NOT NULL DEFAULT 0,
  total_failure_count INTEGER NOT NULL DEFAULT 0,
  policies_json       TEXT NOT NULL DEFAULT '[]',
  source              TEXT NOT NULL DEFAULT 'arf_inbox'
                        CHECK(source IN ('arf_inbox','admin_import')),
  source_message_id   TEXT,
  created_at          TEXT NOT NULL
);
CREATE INDEX idx_tls_rpt_reports_domain   ON tls_rpt_reports(domain, created_at DESC);
CREATE INDEX idx_tls_rpt_reports_created  ON tls_rpt_reports(created_at DESC);
CREATE INDEX idx_tls_rpt_reports_failures ON tls_rpt_reports(total_failure_count DESC, created_at DESC);

CREATE TABLE tls_rpt_failure_summary (
  domain          TEXT NOT NULL,
  day             TEXT NOT NULL,
  result_type     TEXT NOT NULL,
  failed_sessions INTEGER NOT NULL DEFAULT 0,
  reports         INTEGER NOT NULL DEFAULT 0,
  last_seen_at    TEXT NOT NULL,
  PRIMARY KEY (domain, day, result_type)
);
CREATE INDEX idx_tls_rpt_failure_summary_day ON tls_rpt_failure_summary(day DESC);

CREATE TABLE dmarc_aggregate_reports (
  id                TEXT PRIMARY KEY,
  domain            TEXT,
  org_name          TEXT,
  org_email         TEXT,
  report_id         TEXT,
  date_range_begin  TEXT,
  date_range_end    TEXT,
  policy_p          TEXT,
  policy_sp         TEXT,
  policy_pct        INTEGER,
  policy_adkim      TEXT,
  policy_aspf       TEXT,
  total_count       INTEGER NOT NULL DEFAULT 0,
  total_dmarc_pass  INTEGER NOT NULL DEFAULT 0,
  total_dkim_pass   INTEGER NOT NULL DEFAULT 0,
  total_spf_pass    INTEGER NOT NULL DEFAULT 0,
  records_json      TEXT NOT NULL DEFAULT '[]',
  source            TEXT NOT NULL DEFAULT 'arf_inbox'
                      CHECK(source IN ('arf_inbox','admin_import')),
  source_message_id TEXT,
  created_at        TEXT NOT NULL
);
CREATE INDEX        idx_dmarc_reports_domain  ON dmarc_aggregate_reports(domain, created_at DESC);
CREATE INDEX        idx_dmarc_reports_created ON dmarc_aggregate_reports(created_at DESC);
CREATE UNIQUE INDEX uniq_dmarc_aggregate_reports_dedup
  ON dmarc_aggregate_reports(domain, report_id) WHERE report_id IS NOT NULL;

CREATE TABLE dmarc_alignment_rollup (
  domain       TEXT NOT NULL,
  day          TEXT NOT NULL,
  reports      INTEGER NOT NULL DEFAULT 0,
  total_count  INTEGER NOT NULL DEFAULT 0,
  dmarc_pass   INTEGER NOT NULL DEFAULT 0,
  dkim_pass    INTEGER NOT NULL DEFAULT 0,
  spf_pass     INTEGER NOT NULL DEFAULT 0,
  last_seen_at TEXT NOT NULL,
  PRIMARY KEY (domain, day)
);
CREATE INDEX idx_dmarc_rollup_day ON dmarc_alignment_rollup(day DESC);

-- ============================================================================
-- Synthetic health checks + triage events
-- ============================================================================

CREATE TABLE synthetic_runs (
  id         TEXT PRIMARY KEY,
  check_kind TEXT NOT NULL CHECK(check_kind IN (
               'mta_sts_continuity',
               'dkim_self_verify',
               'roundtrip_send',
               'healthz'
             )),
  target     TEXT NOT NULL,
  ok         INTEGER NOT NULL CHECK(ok IN (0,1)),
  latency_ms INTEGER,
  detail     TEXT,
  run_at     TEXT NOT NULL
);
CREATE INDEX idx_synthetic_runs_kind_run_at ON synthetic_runs(check_kind, run_at DESC);
CREATE INDEX idx_synthetic_runs_target      ON synthetic_runs(target, run_at DESC);
CREATE INDEX idx_synthetic_runs_run_at      ON synthetic_runs(run_at DESC);

CREATE TABLE triage_events (
  id                      TEXT PRIMARY KEY,
  message_id              TEXT,
  inbound_alias           TEXT,
  model                   TEXT NOT NULL,
  prompt_hash             TEXT NOT NULL,
  response_json           TEXT NOT NULL,
  category                TEXT NOT NULL,
  severity                TEXT NOT NULL,
  confidence              REAL NOT NULL,
  actionable              INTEGER NOT NULL CHECK(actionable IN (0,1)),
  target_recipient        TEXT,
  target_sender_principal TEXT,
  target_message_id       TEXT,
  summary                 TEXT,
  applied_suppression_id  TEXT,
  operator_verdict        TEXT,
  created_at              TEXT NOT NULL
);
CREATE INDEX idx_triage_events_category   ON triage_events(category, created_at DESC);
CREATE INDEX idx_triage_events_actionable ON triage_events(actionable, created_at DESC);
CREATE INDEX idx_triage_events_severity   ON triage_events(severity, created_at DESC);
CREATE INDEX idx_triage_events_confidence ON triage_events(confidence ASC, created_at DESC);
CREATE INDEX idx_triage_events_created    ON triage_events(created_at DESC);

-- ============================================================================
-- Hybrid policy engine
-- ============================================================================

CREATE TABLE policy_decisions (
  id                     TEXT PRIMARY KEY,
  message_id             TEXT,
  direction              TEXT NOT NULL CHECK(direction IN ('inbound','outbound')),
  stream_type            TEXT NOT NULL CHECK(stream_type IN ('transactional','marketing','agent','inbound')),
  verdict                TEXT NOT NULL CHECK(verdict IN ('pass','pass_warn','hold','block')),
  total_score            INTEGER NOT NULL,
  heuristic_reasons_json TEXT NOT NULL,
  llm_invoked            INTEGER NOT NULL CHECK(llm_invoked IN (0,1)),
  llm_label              TEXT,
  llm_confidence         REAL,
  llm_budget_state       TEXT,
  decided_at             TEXT NOT NULL,
  override_decision_id   TEXT,
  override_admin_id      TEXT,
  override_reason        TEXT
);
CREATE INDEX idx_policy_decisions_message    ON policy_decisions(message_id);
CREATE INDEX idx_policy_decisions_verdict    ON policy_decisions(verdict, decided_at DESC);
CREATE INDEX idx_policy_decisions_dir_stream ON policy_decisions(direction, stream_type, decided_at DESC);
CREATE INDEX idx_policy_decisions_decided    ON policy_decisions(decided_at DESC);

CREATE TABLE held_messages (
  id              TEXT PRIMARY KEY,
  message_id      TEXT,
  direction       TEXT NOT NULL CHECK(direction IN ('inbound','outbound')),
  stream_type     TEXT NOT NULL,
  decision_id     TEXT NOT NULL REFERENCES policy_decisions(id),
  raw_mime_r2_key TEXT NOT NULL,
  hold_reason     TEXT NOT NULL,
  hold_until      TEXT NOT NULL,
  released_at     TEXT,
  released_by     TEXT,
  released_action TEXT CHECK(released_action IN (
                    'released','dropped','expired_auto_drop','expired_auto_release'
                  )),
  created_at      TEXT NOT NULL
);
CREATE INDEX idx_held_messages_open       ON held_messages(released_action, created_at DESC);
CREATE INDEX idx_held_messages_hold_until ON held_messages(hold_until);
CREATE INDEX idx_held_messages_decision   ON held_messages(decision_id);

CREATE TABLE moderation_feedback (
  id                         TEXT PRIMARY KEY,
  decision_id                TEXT NOT NULL REFERENCES policy_decisions(id),
  message_id                 TEXT,
  admin_id                   TEXT NOT NULL,
  action                     TEXT NOT NULL CHECK(action IN (
                               'released_as_legit',
                               'dropped_as_phishing',
                               'dropped_as_spam',
                               'dropped_as_marketing',
                               'reclassified'
                             )),
  original_verdict           TEXT NOT NULL,
  corrected_verdict          TEXT,
  message_summary            TEXT NOT NULL,
  heuristic_reasons_summary  TEXT NOT NULL,
  llm_label_at_decision      TEXT,
  llm_confidence_at_decision REAL,
  admin_notes                TEXT,
  created_at                 TEXT NOT NULL
);
CREATE INDEX idx_moderation_feedback_recent ON moderation_feedback(created_at DESC);
CREATE INDEX idx_moderation_feedback_admin  ON moderation_feedback(admin_id, created_at DESC);
CREATE INDEX idx_moderation_feedback_action ON moderation_feedback(action, created_at DESC);

CREATE TABLE inbound_sender_blocks (
  id                        TEXT PRIMARY KEY,
  mailbox_id                TEXT NOT NULL REFERENCES mailboxes(id),
  sender_address_normalized TEXT NOT NULL,
  reason                    TEXT,
  created_by                TEXT NOT NULL,
  created_at                TEXT NOT NULL,
  UNIQUE(mailbox_id, sender_address_normalized)
);
CREATE INDEX idx_inbound_sender_blocks_mailbox ON inbound_sender_blocks(mailbox_id);

CREATE TABLE policy_config (
  id           TEXT PRIMARY KEY,
  scope_type   TEXT NOT NULL CHECK(scope_type IN ('global','domain','mailbox')),
  scope_target TEXT,
  config_json  TEXT NOT NULL,
  updated_at   TEXT NOT NULL,
  updated_by   TEXT NOT NULL,
  UNIQUE(scope_type, scope_target)
);

-- ============================================================================
-- Better-auth tables (panel sessions)
-- ============================================================================
-- Naming convention: singular + lowercase per better-auth's drizzle adapter.

CREATE TABLE "user" (
  id             TEXT PRIMARY KEY,
  name           TEXT,
  email          TEXT NOT NULL UNIQUE,
  email_verified INTEGER NOT NULL DEFAULT 0,
  image          TEXT,
  -- Panel-specific: cached admin flag set by the OIDC role-sync hook
  -- (apps/panel/src/server/auth/role-sync.ts). Better-auth's INSERT
  -- targets this column on first sign-in; missing it surfaces as
  -- `unable_to_create_user` to the operator.
  admin          INTEGER NOT NULL DEFAULT 0,
  created_at     INTEGER NOT NULL,
  updated_at     INTEGER NOT NULL
);

CREATE TABLE "session" (
  id         TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  expires_at INTEGER NOT NULL,
  token      TEXT NOT NULL UNIQUE,
  ip_address TEXT,
  user_agent TEXT,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX idx_session_user_id ON "session"(user_id);

CREATE TABLE "account" (
  id                       TEXT PRIMARY KEY,
  user_id                  TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  account_id               TEXT NOT NULL,
  provider_id              TEXT NOT NULL,
  access_token             TEXT,
  refresh_token            TEXT,
  id_token                 TEXT,
  access_token_expires_at  INTEGER,
  refresh_token_expires_at INTEGER,
  scope                    TEXT,
  password                 TEXT,
  created_at               INTEGER NOT NULL,
  updated_at               INTEGER NOT NULL,
  UNIQUE(provider_id, account_id, user_id)
);
CREATE INDEX idx_account_user_id ON "account"(user_id);

CREATE TABLE "verification" (
  id         TEXT PRIMARY KEY,
  identifier TEXT NOT NULL,
  value      TEXT NOT NULL,
  expires_at INTEGER NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);
CREATE INDEX idx_verification_identifier ON "verification"(identifier);

CREATE TABLE step_ups (
  user_id     TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
  valid_until INTEGER NOT NULL,
  updated_at  TEXT NOT NULL
);

-- ============================================================================
-- Operators (unified identity: CLI, TUI, Wish SSH all use this table)
-- ============================================================================

CREATE TABLE operators (
  id                   TEXT PRIMARY KEY,
  name                 TEXT NOT NULL,
  email                TEXT NOT NULL UNIQUE,
  ssh_pubkey           TEXT NOT NULL,
  ssh_pubkey_fp_sha256 TEXT NOT NULL UNIQUE,
  api_key_id           TEXT NOT NULL UNIQUE
                         REFERENCES api_keys(id) ON DELETE RESTRICT,
  role                 TEXT NOT NULL DEFAULT 'operator'
                         CHECK(role IN ('admin','operator','readonly')),
  disabled_at          TEXT,
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL,
  last_seen_at         TEXT
);
CREATE INDEX        idx_operators_disabled_at ON operators(disabled_at);
CREATE INDEX        idx_operators_api_key_id  ON operators(api_key_id);
CREATE UNIQUE INDEX uniq_operators_fp_active
  ON operators(ssh_pubkey_fp_sha256) WHERE disabled_at IS NULL;

-- ============================================================================
-- Audit log (in-row chained SHA-256 — see services/api/src/audit.ts)
-- ============================================================================

CREATE TABLE audit_log (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  actor     TEXT NOT NULL,
  action    TEXT NOT NULL CHECK(action IN (
              'bootstrap.consume',
              'bootstrap.webauthn_enrolled',
              'mailbox.create','mailbox.update','mailbox.disable','mailbox.delete',
              'mailbox.expunge',
              'mailbox_sender.create','mailbox_sender.update','mailbox_sender.disable','mailbox_sender.delete',
              'email_sender.create','email_sender.disable',
              'mailbox_receiver.create','mailbox_receiver.update','mailbox_receiver.disable','mailbox_receiver.delete',
              'routing_rule.create','routing_rule.update','routing_rule.delete',
              'api_key.issue','api_key.rotate','api_key.rotate.emergency','api_key.revoke',
              'api_key.revoke.emergency',
              'smtp_credential.issue','smtp_credential.disable','smtp_credential.rotate',
              'mailbox_credential.issue','mailbox_credential.rotate','mailbox_credential.disable',
              'dry_run_rotate',
              'bridge.register','bridge.rotate','bridge.deregister',
              'domain.create','domain.update','domain.disable',
              'domain.verify','domain.verify_incomplete','domain.dkim_rotate',
              'domain.inbound.enable','domain.inbound.disable',
              'domain.outbound.enable','domain.outbound.disable',
              'dkim_key.create','dkim_key.activate','dkim_key.retire',
              'webhook_sub.create','webhook_sub.update','webhook_sub.delete','webhook_sub.replay',
              'webhook_sub.test','webhook_sub.rotate',
              'message.submitted','message.received','message.marked_read','message.expunged',
              'rate_limit.exceeded',
              'cf_zone.configure',
              'mta_sts.enable','mta_sts.disable','mta_sts.promote',
              'tls_rpt.enable','tls_rpt.disable',
              'suppression.create','suppression.disable','suppression.import',
              'message.suppressed','message.sender_suppressed',
              'abuse_event.record',
              'admin.alert.sent',
              'sender_abuse_profile.tier_advance',
              'sender.suppress_auto',
              'tls_rpt_report.ingest',
              'dmarc_aggregate_report.ingest',
              'dmarc.promote','dmarc.pause','dmarc.rollback','dmarc.claim_management',
              'triage.classify',
              'triage.operator_override',
              'policy.decide',
              'policy.override',
              'message.held',
              'message.held_release',
              'message.held_drop',
              'moderation.feedback_recorded',
              'inbound_sender_block.create','inbound_sender_block.delete',
              'tenant.create','tenant.update','tenant.disable','tenant.rotate_pepper',
              'operator.create','operator.update','operator.disable',
              'operator.rotate_key','operator.rotate_pubkey',
              'auth.login','auth.logout'
            )),
  target    TEXT,
  meta      TEXT NOT NULL,
  at        INTEGER NOT NULL,
  prev_hash TEXT NOT NULL,
  row_hash  TEXT NOT NULL
);
CREATE INDEX idx_audit_log_at     ON audit_log(at);
CREATE INDEX idx_audit_log_action ON audit_log(action);
CREATE INDEX idx_audit_log_actor  ON audit_log(actor);

-- ============================================================================
-- Views
-- ============================================================================

CREATE VIEW v_mailbox_summary AS
SELECT
  m.id,
  m.name,
  m.description,
  m.default_sender_id,
  m.created_at,
  m.updated_at,
  m.disabled_at,
  (SELECT COUNT(*) FROM mailbox_senders s
     WHERE s.mailbox_id = m.id AND s.disabled_at IS NULL) AS active_sender_count,
  (SELECT COUNT(*) FROM mailbox_receivers r
     WHERE r.mailbox_id = m.id AND r.enabled = 1 AND r.disabled_at IS NULL) AS active_receiver_count
FROM mailboxes m;

CREATE VIEW v_message_with_latest_attempt AS
SELECT
  msg.*,
  a.id              AS latest_attempt_id,
  a.send_attempt_id AS latest_send_attempt_id,
  a.attempted_at    AS latest_attempt_at,
  a.succeeded       AS latest_attempt_succeeded,
  a.error           AS latest_attempt_error
FROM messages msg
LEFT JOIN (
  SELECT *,
         ROW_NUMBER() OVER (PARTITION BY message_id ORDER BY attempted_at DESC) AS rn
  FROM message_attempts
) a ON a.message_id = msg.id AND a.rn = 1;

CREATE VIEW v_message_delivery_state AS
SELECT
  m.id                                                                 AS message_id,
  m.mailbox_id,
  m.direction,
  m.status                                                             AS message_status,
  COALESCE(SUM(CASE WHEN d.status = 'pending'   THEN 1 ELSE 0 END), 0) AS pending_count,
  COALESCE(SUM(CASE WHEN d.status = 'failed'    THEN 1 ELSE 0 END), 0) AS failed_count,
  COALESCE(SUM(CASE WHEN d.status = 'dlq'       THEN 1 ELSE 0 END), 0) AS dlq_count,
  COALESCE(SUM(CASE WHEN d.status = 'succeeded' THEN 1 ELSE 0 END), 0) AS succeeded_count,
  MAX(d.last_error)                                                     AS worst_error
FROM messages m
LEFT JOIN message_deliveries d ON d.message_id = m.id
GROUP BY m.id;

CREATE VIEW v_credential_usage AS
SELECT
  k.id                  AS api_key_id,
  k.prefix,
  k.status,
  k.rate_limit_per_min,
  k.last_used_at,
  p.id                  AS principal_id,
  p.display_name        AS principal_display_name,
  p.kind                AS principal_kind,
  mb.id                 AS mailbox_id,
  mb.name               AS mailbox_name,
  (SELECT COUNT(*) FROM api_key_sender_scopes s WHERE s.api_key_id = k.id) AS sender_scope_count
FROM api_keys k
JOIN principals p ON p.id = k.principal_id
JOIN mailboxes  mb ON mb.id = p.mailbox_id;

CREATE VIEW v_dlq_age AS
SELECT
  dlq.id,
  dlq.message_id,
  dlq.webhook_sub_id,
  dlq.attempts,
  dlq.last_status_code,
  dlq.last_error,
  dlq.dlq_at,
  dlq.replayed_at,
  dlq.dropped_at,
  CAST((julianday('now') - julianday(dlq.dlq_at)) * 24 AS REAL) AS hours_in_dlq
FROM webhook_dlq dlq
WHERE dlq.replayed_at IS NULL AND dlq.dropped_at IS NULL;

-- ============================================================================
-- Triggers
-- ============================================================================

CREATE TRIGGER trg_mailboxes_updated_at
AFTER UPDATE ON mailboxes
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE mailboxes
  SET    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE  id = NEW.id;
END;

CREATE TRIGGER trg_mail_domains_updated_at
AFTER UPDATE ON mail_domains
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE mail_domains
  SET    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE  id = NEW.id;
END;

CREATE TRIGGER trg_operators_updated_at
AFTER UPDATE ON operators
FOR EACH ROW
WHEN NEW.updated_at = OLD.updated_at
BEGIN
  UPDATE operators
  SET    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  WHERE  id = NEW.id;
END;

PRAGMA foreign_keys = ON;

-- ============================================================================
-- Version stamp
-- ============================================================================
INSERT INTO schema_migrations (version, applied_at, sha)
VALUES (1, strftime('%Y-%m-%dT%H:%M:%fZ', 'now'), '0001_init');
