// Generated by oapi-codegen — DO NOT EDIT.
//
// Until `pnpm --filter @polaris/sdk-codegen run generate` runs `oapi-codegen`
// on a machine with Go installed, this file is a placeholder. The hand-written
// `Client` in `client.go` is the production transport; this file will hold
// the typed model structs and per-operation method signatures once codegen
// runs.
package polarissdk
