// Bridge installer: GET /v1/installer/bridge/<token>
//
// Curl-pipe-able bash that bootstraps a registered bridge on the
// operator's host. The token is a one-shot, opaque, unguessable
// identifier handed to the panel at registration; the panel renders
// the curl command in the fresh-credentials banner. We KV-stash the
// per-token bundle (bridge_id, name, hmac, ts_authkey, deployment
// mode) under `bridge_installer:<token>` with a 1h TTL, then DELETE
// the entry on first read so the same URL can't be replayed.
//
// Public endpoint — no admin auth. Security boundary is the token's
// unguessability (32 bytes from `generateNonce`, base32 Crockford
// per the existing nonce code path).
//
// The script:
//   1. Validates docker + docker-compose presence.
//   2. Writes docker-compose.yml + docker-compose.env to CWD. If files
//      already exist, runs an apt-style diff + per-file prompt:
//      [Y]es to overwrite, [N]o (keep), [d]iff (re-show), [a]bort.
//   3. Writes ./secrets/{bridge_id,hmac_key,ts_authkey} with mode 600.
//   4. Runs `docker compose pull && docker compose up -d`.
//   5. Tails `docker compose logs -f` for the operator.
//
// On any failure mid-flow the script bails with a clear message;
// nothing destructive runs without operator confirmation.

import { Hono } from 'hono';
import type { Env } from '../../env.js';
import { buildError } from '../../errors.js';

export const bridgeInstaller = new Hono<{ Bindings: Env }>();

/** KV key under which a bridge-installer payload lives. */
export function bridgeInstallerKvKey(token: string): string {
  return `bridge_installer:${token}`;
}

/** 1 hour. Enough for operators to walk over to the bridge host and run curl. */
export const BRIDGE_INSTALLER_KV_TTL_SECONDS = 60 * 60;

export interface BridgeInstallerPayload {
  bridge_id: string;
  bridge_name: string;
  hmac_key: string;
  ts_authkey: string | null;
  mode: 'tailscale' | 'public';
  api_url: string;
  // Bridge image tag the script should pull. Defaults to `latest` —
  // the operator can pin via env var if they want.
  image: string;
}

bridgeInstaller.get('/v1/installer/bridge/:token', async (c) => {
  const token = c.req.param('token');
  // Token shape sanity check — same alphabet/length as `generateNonce`.
  if (!/^[0-9A-HJKMNP-TV-Z]{24,128}$/.test(token)) {
    return buildError(c, 'bad_request', 'invalid token format');
  }
  const raw = await c.env.KV_KEY_CACHE.get(bridgeInstallerKvKey(token));
  if (!raw) {
    return buildError(c, 'not_found', 'installer token expired or already consumed');
  }
  // One-shot: delete before we return so a replay can't pick it up.
  // Fire-and-forget — even if delete fails the TTL caps the window.
  c.executionCtx.waitUntil(c.env.KV_KEY_CACHE.delete(bridgeInstallerKvKey(token)));
  let payload: BridgeInstallerPayload;
  try {
    payload = JSON.parse(raw) as BridgeInstallerPayload;
  } catch {
    return buildError(c, 'degraded', 'installer payload corrupted');
  }
  const script = renderInstaller(payload);
  return new Response(script, {
    headers: {
      'content-type': 'text/x-shellscript; charset=utf-8',
      'cache-control': 'private, no-store',
      'x-content-type-options': 'nosniff',
    },
  });
});

function renderInstaller(p: BridgeInstallerPayload): string {
  const composeYml = p.mode === 'tailscale' ? composeTailscale(p) : composePublic(p);
  const composeEnv = composeEnvFile(p);
  // POSIX sh script. Stays portable across Debian/Ubuntu/Alpine.
  // Indented with tabs in source but we emit verbatim — the heredoc
  // bodies preserve formatting because we don't strip leading whitespace.
  return `#!/usr/bin/env sh
# polaris-mail-bridge installer for ${p.bridge_name} (id=${p.bridge_id}).
# Generated by the polaris api; do not edit. The token in your URL is
# one-shot — re-running this curl will 404.
set -eu

POLARIS_BRIDGE_DIR="\${POLARIS_BRIDGE_DIR:-./polaris-mail-bridge}"

say() { printf '\\033[1;36m▶\\033[0m %s\\n' "$*" >&2; }
warn() { printf '\\033[1;33m!\\033[0m %s\\n' "$*" >&2; }
die() { printf '\\033[1;31m✘ %s\\033[0m\\n' "$*" >&2; exit 1; }

command -v docker >/dev/null 2>&1 || die "docker not installed"
if ! docker compose version >/dev/null 2>&1; then
  die "'docker compose' plugin missing — install Docker Compose v2"
fi

say "Installing polaris-mail-bridge '${p.bridge_name}' into $POLARIS_BRIDGE_DIR"
mkdir -p "$POLARIS_BRIDGE_DIR"
cd "$POLARIS_BRIDGE_DIR"

write_or_prompt() {
  # $1 = destination filename
  # $2 = new content (via stdin redirection — caller pipes it)
  dst="$1"
  new_content="$2"
  if [ ! -e "$dst" ]; then
    printf '%s' "$new_content" > "$dst"
    say "wrote $dst (new)"
    return 0
  fi
  if [ "$(cat "$dst")" = "$new_content" ]; then
    say "$dst unchanged — skipping"
    return 0
  fi
  warn "$dst differs from the installer's version."
  while :; do
    printf '  [Y]es overwrite / [N]o keep / [d]iff / [a]bort? ' >&2
    read REPLY </dev/tty || REPLY=N
    case "$REPLY" in
      Y|y|"")
        printf '%s' "$new_content" > "$dst"
        say "overwrote $dst"; return 0 ;;
      N|n)
        say "kept existing $dst"; return 0 ;;
      d|D)
        tmp="$(mktemp)"
        printf '%s' "$new_content" > "$tmp"
        diff -u "$dst" "$tmp" || true
        rm -f "$tmp" ;;
      a|A)
        die "aborted by operator" ;;
    esac
  done
}

COMPOSE_YML=$(cat <<'__POLARIS_COMPOSE_YML_EOF__'
${composeYml}__POLARIS_COMPOSE_YML_EOF__
)
COMPOSE_ENV=$(cat <<'__POLARIS_COMPOSE_ENV_EOF__'
${composeEnv}__POLARIS_COMPOSE_ENV_EOF__
)

write_or_prompt docker-compose.yml "$COMPOSE_YML"
write_or_prompt docker-compose.env "$COMPOSE_ENV"

say "Writing ./secrets/ (mode 600)"
mkdir -p secrets
chmod 700 secrets
umask 077
printf '%s' '${p.bridge_id}' > secrets/bridge_id
printf '%s' '${p.hmac_key}' > secrets/hmac_key
${
  p.ts_authkey != null
    ? `printf '%s' '${p.ts_authkey}' > secrets/ts_authkey`
    : `# (no ts_authkey — TS minting not configured server-side)`
}
chmod 600 secrets/*

say "docker compose pull"
docker compose pull
say "docker compose up -d"
docker compose up -d

say "Streaming logs (Ctrl-C to detach; bridge keeps running)"
docker compose logs -f
`;
}

// Compose snippets — keep aligned with the panel templates in
// `apps/panel/src/client/pages/bridges/BridgeConnectionCard.tsx`.
// Both surfaces emit the same shape so operators see one set of
// conventions.

function composeTailscale(p: BridgeInstallerPayload): string {
  const tsHost = `${p.bridge_name}-mail`;
  return `# docker-compose.yml — bridge + Tailscale sidecar
networks:
  polaris-mail-net:
    driver: bridge

services:
  tailscale:
    image: tailscale/tailscale:stable
    container_name: polaris-mail
    hostname: ${tsHost}
    restart: unless-stopped
    networks: [polaris-mail-net]
    cap_add: [NET_ADMIN, NET_RAW]
    devices: ['/dev/net/tun:/dev/net/tun']
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_USERSPACE: 'false'
      TS_EXTRA_ARGS: --advertise-tags=tag:polaris-mail
      TS_AUTHKEY_FILE: /run/secrets/ts_authkey
    volumes:
      - ts-state:/var/lib/tailscale
      - ./secrets:/run/secrets:ro

  bridge:
    image: ${p.image}
    container_name: polaris-mail-bridge
    restart: unless-stopped
    network_mode: 'service:tailscale'
    depends_on:
      - tailscale
    env_file: docker-compose.env
    environment:
      BRIDGE_POLARIS_BRIDGE_ID_FILE: /run/secrets/bridge_id
      BRIDGE_POLARIS_HMAC_KEY_FILE: /run/secrets/hmac_key
    volumes:
      - ./secrets:/run/secrets:ro
      - bridge-certs:/var/lib/polaris-bridge/certs
      - bridge-data:/var/lib/polaris-bridge
      - bridge-logs:/var/log/polaris-bridge

volumes:
  ts-state:
  bridge-certs:
  bridge-data:
  bridge-logs:
`;
}

function composePublic(p: BridgeInstallerPayload): string {
  return `# docker-compose.yml — bridge on public host (no Tailscale)
services:
  bridge:
    image: ${p.image}
    container_name: polaris-mail-bridge
    restart: unless-stopped
    network_mode: host
    env_file: docker-compose.env
    environment:
      BRIDGE_POLARIS_BRIDGE_ID_FILE: /run/secrets/bridge_id
      BRIDGE_POLARIS_HMAC_KEY_FILE: /run/secrets/hmac_key
    volumes:
      - ./secrets:/run/secrets:ro
      - bridge-certs:/var/lib/polaris-bridge/certs
      - bridge-data:/var/lib/polaris-bridge
      - bridge-logs:/var/log/polaris-bridge

volumes:
  bridge-certs:
  bridge-data:
  bridge-logs:
`;
}

function composeEnvFile(p: BridgeInstallerPayload): string {
  return `# docker-compose.env — referenced by docker-compose.yml via env_file.
# No secrets in here; the HMAC key + bridge id (and TS auth key) live
# as files under ./secrets/ that the bridge reads via *_FILE env vars.

BRIDGE_NAME=${p.bridge_name}
BRIDGE_POLARIS_API_URL=${p.api_url}
`;
}
