// Docusaurus v3 configuration for docs.mail.plrs.im.
//
// Phase A of PR 12 wires:
//   * brand theme port (src/css/custom.css) — cosmos-indigo surface +
//     aurora-violet accent; siblings to support-portal & ExpressCharge.
//   * docusaurus-plugin-openapi-docs — generates MDX into
//     docs/reference/api/ from ../../openapi/polaris-mail.yaml. The output
//     directory is gitignored and regenerated by `docs:gen-api` (chained
//     from `build:client`).
//   * Pagefind index — produced post-build by `pagefind --site build`;
//     the swizzled SearchBar (src/theme/SearchBar) mounts the UI.
//
// The static build is served as-is by a thin Hono Worker
// (see src/server/index.ts) with a redirect table for legacy URLs.
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import type * as OpenApiPlugin from 'docusaurus-plugin-openapi-docs';
import { themes as prismThemes } from 'prism-react-renderer';

const config: Config = {
  title: 'polaris-mail',
  tagline: 'Managed email service for the polaris-* family',
  url: 'https://docs.mail.plrs.im',
  baseUrl: '/',
  favicon: 'img/favicon.ico',

  organizationName: 'polaris',
  projectName: 'polaris-mail',

  // Fail the build on broken links / anchors. The site is small enough that
  // this is cheap insurance against IA drift.
  onBrokenLinks: 'throw',
  onBrokenAnchors: 'throw',

  // Docusaurus 3.10+ moved onBrokenMarkdownLinks under `markdown.hooks`.
  markdown: {
    hooks: {
      onBrokenMarkdownLinks: 'throw',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  // `docusaurus-theme-openapi-docs` requires the sass theme plugin to be
  // present — listed here so we don't have to add it in `themes` too.
  plugins: [
    // Inline plugin: silence the third-party `@theme/Schema` and
    // `@theme/SchemaTabs` `"export 'default' was not found"` warnings emitted
    // by `docusaurus-theme-openapi-docs@5` against Docusaurus 3.10's stricter
    // MDX export resolution. These swizzleable theme components DO exist at
    // runtime — they're just emitted as CJS interop shims that webpack flags
    // as missing `default` exports during the bundle pass. Tracked upstream;
    // there's no behavioural impact (the components render correctly in the
    // browser). Filtering keeps `pnpm -r build` warning-free.
    () => ({
      name: 'suppress-openapi-theme-export-warnings',
      configureWebpack() {
        return {
          ignoreWarnings: [
            (warning) =>
              typeof warning.message === 'string' &&
              warning.message.includes("export 'default'") &&
              (warning.message.includes('@theme/Schema') ||
                warning.message.includes('@theme/SchemaTabs')),
          ],
        };
      },
    }),
    'docusaurus-plugin-sass',
    [
      'docusaurus-plugin-openapi-docs',
      {
        id: 'openapi',
        // The plugin pre-processes the generated MDX through this docs
        // plugin id. We rely on the preset-classic's default `docs` plugin.
        docsPluginId: 'classic',
        config: {
          polarisApi: {
            specPath: '../../openapi/polaris-mail.yaml',
            outputDir: 'content/reference/api',
            sidebarOptions: {
              groupPathsBy: 'tag',
              categoryLinkSource: 'tag',
            },
            // Use the plugin's built-in MDX template (set when omitted) so
            // we don't have to vendor a mustache file. The output is the
            // standard request/response panel layout.
            showSchemas: true,
          } satisfies OpenApiPlugin.Options,
        },
      },
    ],
  ],

  themes: ['docusaurus-theme-openapi-docs'],

  presets: [
    [
      'classic',
      {
        docs: {
          path: 'content',
          routeBasePath: '/',
          sidebarPath: './sidebars.ts',
          // Edit-link points at the source repo so contributors can fix
          // typos via the GitHub UI.
          editUrl: 'https://github.com/vladzaharia/polaris-email/edit/main/apps/docs/',
          // openapi-docs ships a custom MDX docItem with the request +
          // response panels. Pointing it here makes generated pages render
          // with that theme component instead of the default.
          docItemComponent: '@theme/ApiItem',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    colorMode: {
      defaultMode: 'dark',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'polaris-mail',
      logo: {
        alt: 'polaris-mail',
        src: 'img/logo.svg',
      },
      items: [
        {
          to: '/get-started',
          label: 'Get started',
          position: 'left',
        },
        {
          to: '/developers',
          label: 'Developers',
          position: 'left',
        },
        {
          to: '/operators',
          label: 'Operators',
          position: 'left',
        },
        {
          to: '/reference',
          label: 'Reference',
          position: 'left',
        },
        {
          href: 'https://github.com/vladzaharia/polaris-email',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            { label: 'Get started', to: '/get-started' },
            { label: 'For developers', to: '/developers' },
            { label: 'For operators', to: '/operators' },
            { label: 'Reference', to: '/reference' },
          ],
        },
        {
          title: 'Project',
          items: [
            { label: 'GitHub', href: 'https://github.com/vladzaharia/polaris-email' },
            { label: 'Security', to: '/security' },
            { label: 'Changelog', to: '/changelog' },
            { label: 'Contributing', to: '/contributing' },
          ],
        },
        {
          title: 'polaris-* family',
          items: [
            { label: 'polaris-support', href: 'https://support.plrs.im' },
            { label: 'polaris-mail API', href: 'https://api.mail.plrs.im' },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} polaris-mail contributors. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.vsDark,
      darkTheme: prismThemes.vsDark,
      additionalLanguages: [
        // Note: Prism doesn't ship a `jsonc` grammar; `json` covers our
        // wrangler.jsonc snippets well enough.
        'typescript',
        'tsx',
        'go',
        'bash',
        'json',
        'toml',
        'yaml',
        'http',
        'shell-session',
        'sql',
      ],
    },
    // Docusaurus's classic theme expects an Algolia config when the
    // SearchBar swizzle is removed; we ship a custom SearchBar
    // (src/theme/SearchBar) backed by Pagefind, so nothing more to set
    // here.
  } satisfies Preset.ThemeConfig,
};

export default config;
