// Sidebar configuration. The autogenerated style reads `_category_.json`
// in each top-level docs folder for its label + position. PR 12 will
// likely replace this with hand-curated sidebars once the real content
// lands.
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
