import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: 'doc',
      id: 'reference/api/polaris-email-api',
    },
    {
      type: 'category',
      label: 'UNTAGGED',
      items: [
        {
          type: 'doc',
          id: 'reference/api/liveness-probe',
          label: 'Liveness probe',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/submit-a-message-json-or-rfc-822',
          label: 'Submit a message (JSON or RFC822)',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/list-messages',
          label: 'List messages',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/fetch-one-message',
          label: 'Fetch one message',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/list-mailboxes',
          label: 'List mailboxes',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/create-a-mailbox',
          label: 'Create a mailbox',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/get-mailbox-detail-with-nested-senders-receivers-principals-webhook-subs',
          label: 'Get mailbox detail (with nested senders/receivers/principals/webhook_subs)',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/update-mailbox-fields',
          label: 'Update mailbox fields',
          className: 'api-method patch',
        },
        {
          type: 'doc',
          id: 'reference/api/soft-disable-a-mailbox',
          label: 'Soft-disable a mailbox',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/re-enable-a-mailbox',
          label: 'Re-enable a mailbox',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/create-a-mailbox-sender',
          label: 'Create a mailbox_sender',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/soft-disable-a-mailbox-sender',
          label: 'Soft-disable a mailbox_sender',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'reference/api/create-a-mailbox-receiver',
          label: 'Create a mailbox_receiver',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/update-a-mailbox-receiver',
          label: 'Update a mailbox_receiver',
          className: 'api-method patch',
        },
        {
          type: 'doc',
          id: 'reference/api/soft-disable-a-mailbox-receiver',
          label: 'Soft-disable a mailbox_receiver',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'reference/api/issue-an-api-key-bound-to-a-mailbox-principal',
          label: 'Issue an api key bound to a mailbox principal',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/rotate-an-api-key',
          label: 'Rotate an api key',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/revoke-an-api-key',
          label: 'Revoke an api key',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/create-a-webhook-subscription',
          label: 'Create a webhook subscription',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/mail-bridge-credential-mirror',
          label: 'Mail-bridge credential mirror',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/one-time-seed-of-the-first-admin-key-signed-with-polaris-secret-a',
          label: 'One-time seed of the first admin key. Signed with POLARIS_SECRET_A.',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/list-operators',
          label: 'List operators',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/create-operator-atomically-principals-api-keys-operators-rows',
          label: 'Create operator (atomically: principals + api_keys + operators rows)',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/lookup-operator-by-ssh-pubkey-fingerprint-wish-hot-path',
          label: 'Lookup operator by SSH pubkey fingerprint (Wish hot path)',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/show-one-operator-includes-full-ssh-pubkey',
          label: 'Show one operator (includes full SSH pubkey)',
          className: 'api-method get',
        },
        {
          type: 'doc',
          id: 'reference/api/update-operator-name-role-disabled-flag',
          label: 'Update operator name / role / disabled flag',
          className: 'api-method patch',
        },
        {
          type: 'doc',
          id: 'reference/api/soft-disable-operator-alias-for-patch-with-disabled-true',
          label: 'Soft-disable operator (alias for PATCH with disabled=true)',
          className: 'api-method delete',
        },
        {
          type: 'doc',
          id: 'reference/api/rotate-the-operators-underlying-api-key-returns-new-bearer-once',
          label: "Rotate the operator's underlying api_key (returns new bearer once)",
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/replace-the-operators-ssh-pubkey-api-key-unchanged',
          label: "Replace the operator's SSH pubkey (api_key unchanged)",
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/validate-an-operator-bearer-and-return-cached-operator-profile-cli-login',
          label: 'Validate an operator bearer and return cached operator profile (CLI login)',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/audit-only-logout-signal-writes-auth-logout-row-no-server-side-revocation',
          label: 'Audit-only logout signal (writes auth.logout row; no server-side revocation)',
          className: 'api-method post',
        },
        {
          type: 'doc',
          id: 'reference/api/webhook-delivered-to-a-subscriber',
          label: 'Webhook delivered to a subscriber',
          className: 'api-method event',
        },
      ],
    },
    {
      type: 'category',
      label: 'Schemas',
      items: [
        {
          type: 'doc',
          id: 'reference/api/schemas/ulid',
          label: 'Ulid',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/keyscope',
          label: 'KeyScope',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/operator',
          label: 'Operator',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/operatorcreaterequest',
          label: 'OperatorCreateRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/operatorissueresponse',
          label: 'OperatorIssueResponse',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/operatorupdaterequest',
          label: 'OperatorUpdateRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/operatorrotatepubkeyrequest',
          label: 'OperatorRotatePubkeyRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/loginresponse',
          label: 'LoginResponse',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/error',
          label: 'Error',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/messageattachment',
          label: 'MessageAttachment',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/messageauth',
          label: 'MessageAuth',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/message',
          label: 'Message',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/sendrequestattachment',
          label: 'SendRequestAttachment',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/sendrequest',
          label: 'SendRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/sendresponse',
          label: 'SendResponse',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/messagelist',
          label: 'MessageList',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/webhookeventtype',
          label: 'WebhookEventType',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/webhookenvelope',
          label: 'WebhookEnvelope',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/mailbox',
          label: 'Mailbox',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/mailboxsender',
          label: 'MailboxSender',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/mailboxreceiver',
          label: 'MailboxReceiver',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/maildomain',
          label: 'MailDomain',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/updatemaildomainrequest',
          label: 'UpdateMailDomainRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/verifycheck',
          label: 'VerifyCheck',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/verifyresponse',
          label: 'VerifyResponse',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/createmailboxrequest',
          label: 'CreateMailboxRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/createmailboxsenderrequest',
          label: 'CreateMailboxSenderRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/createmailboxreceiverrequest',
          label: 'CreateMailboxReceiverRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/issueapikeyrequest',
          label: 'IssueApiKeyRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/issueapikeyresponse',
          label: 'IssueApiKeyResponse',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/rotaterequest',
          label: 'RotateRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/rotateresponse',
          label: 'RotateResponse',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/createwebhooksubrequest',
          label: 'CreateWebhookSubRequest',
          className: 'schema',
        },
        {
          type: 'doc',
          id: 'reference/api/schemas/bridgecredentialsresponse',
          label: 'BridgeCredentialsResponse',
          className: 'schema',
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
