package bridge

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"

	"github.com/vladzaharia/polaris-email/apps/polaris-cli/internal/setup/platform"
)

// RenderContext is the data the templates see. Most fields shadow
// BridgeSetupInput; the few extras (GeneratedAt, CLIVersion, TLSMode,
// AccessClient*) are computed by NewRenderContext.
type RenderContext struct {
	GeneratedBanner string
	GeneratedAt     string
	CLIVersion      string

	Mode               string
	BridgeName         string
	Environment        string
	PolarisAPIURL      string
	TLSSource          string
	TLSMode            string // bridge.toml: "local" | "tailscale"
	FQDN               string
	SMTPSPort          int
	IMAPPort           int
	WebhookPort        int
	TLSDir             string
	ACMEEmail          string
	Region             string
	ImageTag           string
	AccessClientID     string
	AccessClientSecret string
}

// NewRenderContext maps BridgeSetupInput onto the template data. It
// deliberately does not touch the on-disk filesystem — pure function so
// golden tests stay deterministic. cliVersion stamps the README banner;
// access* are the registration response (or empty for example
// rendering).
func NewRenderContext(in *BridgeSetupInput, cliVersion, accessClientID, accessClientSecret string, now time.Time) *RenderContext {
	tlsMode := "local"
	if in.Mode == ModeTailscale && in.TLSSource == TLSTailscaleSidecar {
		tlsMode = "tailscale"
	}
	return &RenderContext{
		GeneratedBanner:    "Generated by polaris-cli setup bridge — do not edit by hand",
		GeneratedAt:        now.UTC().Format(time.RFC3339),
		CLIVersion:         cliVersion,
		Mode:               string(in.Mode),
		BridgeName:         in.BridgeName,
		Environment:        in.Environment,
		PolarisAPIURL:      in.PolarisAPIURL,
		TLSSource:          string(in.TLSSource),
		TLSMode:            tlsMode,
		FQDN:               in.FQDN,
		SMTPSPort:          in.SMTPSPort,
		IMAPPort:           in.IMAPPort,
		WebhookPort:        in.WebhookPort,
		TLSDir:             in.TLSDir,
		ACMEEmail:          in.ACMEEmail,
		Region:             in.Region,
		ImageTag:           in.ImageTag,
		AccessClientID:     accessClientID,
		AccessClientSecret: accessClientSecret,
	}
}

// RenderedFile is one output file from a Render call.
type RenderedFile struct {
	RelPath string      // path relative to the project dir
	Mode    os.FileMode // file mode (0o600 for .env, 0o644 for the rest)
	Body    []byte
}

// Render produces every artefact the wizard writes for the given input.
// The result is the *content* — no disk IO yet (Write does that).
func Render(rc *RenderContext) ([]RenderedFile, error) {
	composeTmpl := "templates/compose.local.yml.tmpl"
	if rc.Mode == string(ModeTailscale) {
		composeTmpl = "templates/compose.tailscale.yml.tmpl"
	}
	files := []struct {
		out  string
		src  string
		mode os.FileMode
	}{
		{"docker-compose.yml", composeTmpl, 0o644},
		{".env", "templates/env.tmpl", 0o600},
		{"bridge.toml", "templates/bridge.toml.tmpl", 0o644},
		{"README.md", "templates/README.md.tmpl", 0o644},
	}
	out := make([]RenderedFile, 0, len(files))
	for _, f := range files {
		body, err := renderOne(f.src, rc)
		if err != nil {
			return nil, fmt.Errorf("render %s: %w", f.out, err)
		}
		out = append(out, RenderedFile{RelPath: f.out, Mode: f.mode, Body: body})
	}
	return out, nil
}

func renderOne(name string, rc *RenderContext) ([]byte, error) {
	raw, err := Templates.ReadFile(name)
	if err != nil {
		return nil, err
	}
	t, err := template.New(filepath.Base(name)).Option("missingkey=error").Parse(string(raw))
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, rc); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// WriteFiles writes rendered files into dir. The bridge.toml and
// docker-compose.yml are 0644; .env is 0600 (it contains the Cloudflare
// Access secret in the rendered form).
func WriteFiles(dir string, files []RenderedFile) error {
	for _, f := range files {
		if err := platform.AtomicWrite(filepath.Join(dir, f.RelPath), f.Body, f.Mode); err != nil {
			return fmt.Errorf("write %s: %w", f.RelPath, err)
		}
	}
	return nil
}
