package bridge

import "embed"

// Templates is the embed.FS rooted at this package's templates/
// directory. The contents are the source of truth for both:
//
//   - the operator-facing files the wizard renders into <dir>/
//   - the example compose files checked into apps/mail-bridge/
//     (regenerated by `make compose-examples`)
//
//go:embed templates/*.tmpl
var Templates embed.FS
