-- polaris-email D1 schema v3: smtp_credentials hash-column naming fix.
--
-- Background: an earlier draft of 0002 created smtp_credentials with a column
-- named `password_argon2id`, but the codebase's hashSecret() is PBKDF2-SHA256
-- (PHC-prefixed `$pbkdf2-sha256$…`), not Argon2id. The reuse decision (one
-- primitive for api-key + smtp-credential hashing) was correct; the column
-- name lied.
--
-- 0002 has since been amended in-place to declare the column as
-- `password_hash` directly, so fresh databases never see the misnamed column.
-- For any environment that had already applied the original 0002 prior to the
-- amendment, run the following manually (idempotent against fresh schemas
-- where the column will not exist):
--
--   ALTER TABLE smtp_credentials RENAME COLUMN password_argon2id TO password_hash;
--
-- SQLite 3.25+ supports RENAME COLUMN; D1 ships SQLite 3.45+.
-- This file itself is intentionally a no-op so `cat 000?_*.sql | sqlite3`
-- pipelines apply cleanly against a database where 0002 already declared
-- the renamed column.
--
-- Append-only migration. Never edit; add 0004_*.sql for further changes.

PRAGMA foreign_keys = ON;
-- (no DDL — see comment block above for the manual catch-up statement.)
