package config

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// DefaultPath is the canonical .env.deploy location relative to the
// repo root.
const DefaultPath = ".env.deploy"

// Load parses a shell-sourceable .env.deploy file. The format mirrors
// what bin/configure.sh writes:
//
//   - blank lines and `#`-prefixed comments are skipped
//   - `KEY=VALUE` lines are accepted; VALUE may be optionally quoted
//     with double or single quotes
//   - VALUEs are NOT shell-expanded (no $var, no command substitution).
//     The shell script doesn't write expandable forms, but if an
//     operator hand-edits one in, we surface the literal text.
//
// Missing file → ([nil-Config-pointer], os.ErrNotExist). Callers that
// want a defaulted config on missing-file should check errors.Is and
// fall back to &Config{}.
//
// Unknown keys are silently dropped — preflight only cares about the
// keys we know about. (A future PR could promote this to a warn.)
func Load(path string) (*Config, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return parse(f)
}

// LoadOrDefault returns the parsed config if the file exists, or a
// zero-valued *Config when the file is missing. Other errors propagate.
// Used by `setup infra configure` so it can seed the prompt loop even
// on a first-run machine.
func LoadOrDefault(path string) (*Config, error) {
	c, err := Load(path)
	if err == nil {
		return c, nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return &Config{}, nil
	}
	return nil, err
}

// parse reads .env.deploy lines from r. Exposed (lowercase) for tests
// that want to feed bytes directly without round-tripping the
// filesystem.
func parse(r io.Reader) (*Config, error) {
	c := &Config{}
	sc := bufio.NewScanner(r)
	// .env.deploy can hold large secrets (B2 keys are ~64 chars); the
	// default 64KB buffer is plenty but be explicit so a regression
	// doesn't break things silently.
	sc.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		// Drop a leading `export ` prefix in case the operator
		// hand-rewrote a line — bin/configure.sh doesn't emit one but
		// being lenient on read is cheap.
		line = strings.TrimPrefix(line, "export ")
		eq := strings.IndexByte(line, '=')
		if eq <= 0 {
			return nil, fmt.Errorf("config: malformed line %d: %q", lineNo, line)
		}
		key := strings.TrimSpace(line[:eq])
		value := strings.TrimSpace(line[eq+1:])
		value = unquote(value)
		c.setField(key, value)
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("config: read: %w", err)
	}
	return c, nil
}

// unquote strips a single pair of surrounding double or single quotes
// from a value, mirroring bash's behavior on `KEY="value"` (the quotes
// are syntactic, not part of the value). Mismatched quotes are left
// alone — they're almost certainly a hand-edit mistake.
func unquote(v string) string {
	if len(v) < 2 {
		return v
	}
	first, last := v[0], v[len(v)-1]
	if (first == '"' && last == '"') || (first == '\'' && last == '\'') {
		return v[1 : len(v)-1]
	}
	return v
}

// Save atomically rewrites path with c's contents in [FieldOrder].
// File mode is 0600 — secrets live here. Parent directory is created
// with 0700 if it doesn't exist (rare but possible on a fresh checkout
// where the operator passed a non-default path).
//
// The "save after every prompt" property of bin/configure.sh — Ctrl-C
// halfway through is durable — is preserved by calling Save() from
// each prompt-loop iteration, not by Save() doing anything clever
// internally. The function is safe to call repeatedly.
func Save(path string, c *Config) error {
	if c == nil {
		return errors.New("config: Save requires a non-nil *Config")
	}
	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o700); err != nil {
			return fmt.Errorf("config: mkdir %s: %w", dir, err)
		}
	}

	var buf bytes.Buffer
	buf.WriteString("# polaris-email deploy config — generated by `polaris-email setup infra configure`.\n")
	buf.WriteString("# Re-run safely. DO NOT COMMIT. .env.deploy is gitignored.\n")
	m := c.AsMap()
	for _, key := range FieldOrder {
		fmt.Fprintf(&buf, "%s=%s\n", key, quoteValue(m[key]))
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("config: write temp: %w", err)
	}
	// Even when WriteFile created the file with 0600, an existing tmp
	// could carry stale perms — force them once more.
	if err := os.Chmod(tmp, 0o600); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("config: chmod temp: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("config: rename: %w", err)
	}
	return nil
}

// quoteValue picks a quoting strategy that round-trips through our
// own parser AND is safe to `source` from bash.
//
// Strategy:
//   - Empty values are written as `""` to keep the parsed line non-empty.
//   - Values free of single quotes get wrapped in single quotes — bash
//     treats single-quoted strings literally, so $, `, \, and " all
//     pass through unchanged. Our parser strips the outer quotes and
//     hands the operator the literal value back.
//   - Values containing a single quote can't be single-quoted as-is, so
//     we fall back to a double-quoted form with the four metacharacters
//     escaped. (Operators who paste a value containing both `'` and `"`
//     plus a backslash will get a working but mildly mangled string —
//     a rare-enough case that an error message is overkill.)
//
// The choice deliberately favors not escaping over escaping: B2 keys
// and OIDC client secrets typically contain `+/=` and other base64-ish
// punctuation that we want to write verbatim.
func quoteValue(v string) string {
	if v == "" {
		return `""`
	}
	if !strings.ContainsRune(v, '\'') {
		return "'" + v + "'"
	}
	// Has a single quote — must double-quote and escape `\`, `"`, `$`,
	// and backtick. The parser strips the outer `"` and our unquote()
	// helper doesn't process escapes, so we ALSO have to keep our
	// escapes minimal to avoid a re-escaping problem.
	//
	// Practical observation: the .env.deploy fields that might contain
	// quotes are URLs (no quotes), B2 secrets (no quotes), tokens (no
	// quotes), and free-form addresses. The single-quoted branch above
	// handles ~all real cases; this branch is the last-resort fallback.
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		`$`, `\$`,
		"`", "\\`",
	)
	return `"` + r.Replace(v) + `"`
}
